### ISSUE TITLE
REPT Macro with SUBPAGE does not work together

### ISSUE THREAD

**Issue by jamque** [Fubukimaru/asMSX#53] opened 2020-01-06 17:33 UTC
This code to create a group of pages in blank...

PAGE=1
REPT 63
SUBPAGE PAGE AT 06000h
PAGE = PAGE + 1
ENDR

Makes error in SUBPAGE stament : Parsing error: syntax error

You can not use ASMSX Variables in MACROS

**Comment by duhow** [comment] 2020-12-06 22:02
When naming the variable with `@@`, code does work - refering to the variable.
But in this case, doing the repeat with megaROM define and subpage, causes a segmention fault (crash).
You can try by uncommenting the `.megarom` code.
```
;.megarom konamiscc

PAGE=1
REPT 63
SUBPAGE @@PAGE AT 06000h
PAGE = PAGE + 1
ENDR
```

By manually doing the `.megarom` and `SUBPAGE` function calls, binary file is created successfully.

**Comment by duhow** [comment] 2020-12-06 23:02
:warning: Ok, found that the issue is because of using the variable name `PAGE`, which seems to collide with **function** `.PAGE`.
When renaming variable to another name (`PAGINA`), code works.

```
.megarom konamiscc
PAGINA = 1
REPT 63
SUBPAGE PAGINA AT 06000h
PAGINA = PAGINA + 1
ENDR
```

**Comment by Fubukimaru** [comment] 2020-12-07 08:08
Perfect. Then there is no bug here. I'm closing it!

Thanks for the check!

**Closed by Fubukimaru** 2020-12-07 08:08 UTC
Labels: bug
